export default [
    {
        id:1,
        profile_url:"./images/avatar-mark-webber.webp",
        profile_name:"Mark Webber ",
        paragraph:"reacted to your recent post",
        time :"1m ago",
        topic:"My first tournament today!",
        status:true,
    },
    {
        id:2,
        profile_url:"./images/avatar-angela-gray.webp",
        profile_name:"Angela Gray ",
        paragraph:"followed you ",
        time :"5m ago",
        topic:"",
        status:true,
    },
    {
        id:3,
        profile_url:"./images/avatar-jacob-thompson.webp",
        profile_name:"Jacob Thompson ",
        paragraph:"has joined your group ",
        time :"1 day ago",
        topic:"Chess Club",
        status:true,
    },
    {
        id:4,
        profile_url:"./images/avatar-rizky-hasanuddin.webp",
        profile_name:"Rizky Hasanuddin ",
        paragraph:"sent you a private message ",
        time :"5 day ago",
        topic:"",
        status:false,
    },
    {
        id:5,
        profile_url:"./images/avatar-kimberly-smith.webp",
        profile_name:"Kimberly Smith ",
        paragraph:"commented on your picture ",
        time :"1 week ago",
        topic:"",
        status:false,
    },
    {
        id:6,
        profile_url:"./images/avatar-nathan-peterson.webp",
        profile_name:"Nathan Peterson ",
        paragraph:"reacted to your recent post ",
        time :"2 weeks ago",
        topic:"5 end-game strategies to increase your win rate",
        status:true,
    },
    {
        id:7,
        profile_url:"./images/avatar-anna-kim.webp",
        profile_name:"Anna Kim ",
        paragraph:"left the group ",
        time :"2 weeks ago",
        topic:"Chess Club",
        status:true,
    },
    {
        id:8,
        profile_url:"./images/avatar-anna-kim.webp",
        profile_name:"Anna Kim ",
        paragraph:"joined the group ",
        time :"3 weeks ago",
        topic:"Chess Club",
        status:true,
    }
    
]